# Generated by Django 2.0.2 on 2018-02-08 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('EN', '英文'), ('CN', '中文')], max_length=2)),
                ('for_age', models.IntegerField(choices=[(1, '0~2岁'), (2, '3~5岁'), (3, '6~8岁'), (4, '9~12岁'), (5, '13+岁')])),
                ('subject', models.CharField(choices=[('nature', '自然'), ('history', '历史'), ('math', '数学'), ('geography', '地理'), ('biology', '生物')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birth_year', models.IntegerField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('reader_type', models.IntegerField(choices=[(0, '游客'), (1, '年卡'), (2, '月卡'), (3, '次卡')], default=0)),
                ('deposit_amount', models.FloatField(default=0)),
                ('register_date', models.DateField()),
                ('expiry_date', models.DateField(default=datetime.date(2000, 1, 1))),
            ],
        ),
    ]
