# Generated by Django 2.0.2 on 2018-03-13 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('bookname', models.CharField(blank=True, max_length=80)),
                ('series_name', models.CharField(blank=True, max_length=30)),
                ('author', models.CharField(blank=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', '英文'), ('CN', '中文')], default='EN', max_length=2)),
                ('for_age', models.IntegerField(choices=[(1, '0~2岁'), (2, '3~5岁'), (3, '6~8岁'), (4, '9~12岁'), (5, '13+岁')], default=1)),
                ('subject', models.IntegerField(choices=[(1, '自然'), (2, '历史'), (3, '数学'), (4, '地理'), (5, '生物'), (6, '故事/小说'), (7, '其他')], default=1)),
                ('pages', models.IntegerField(blank=True, default=0)),
                ('book_count', models.IntegerField(blank=True, default=1)),
                ('image_sm', models.CharField(blank=True, max_length=26)),
                ('image_bg', models.CharField(blank=True, max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Bookcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=80)),
                ('add_time', models.DateField(auto_now=True)),
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=24)),
                ('book_limit', models.IntegerField(blank=True, default=0)),
                ('birth_year', models.IntegerField(blank=True, default=2000)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('reader_type', models.IntegerField(choices=[(0, '游客'), (1, '年卡'), (2, '月卡'), (3, '次卡')], default=0)),
                ('deposit_amount', models.FloatField(default=0)),
                ('register_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(max_length=11)),
                ('randomchar', models.CharField(max_length=6)),
            ],
        ),
    ]
