# Generated by Django 2.0.2 on 2018-02-08 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='for_age',
            field=models.IntegerField(choices=[(1, '0~2岁'), (2, '3~5岁'), (3, '6~8岁'), (4, '9~12岁'), (5, '13+岁')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('EN', '英文'), ('CN', '中文')], default='CN', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('nature', '自然'), ('history', '历史'), ('math', '数学'), ('geography', '地理'), ('biology', '生物')], default='nature', max_length=12),
        ),
        migrations.AlterField(
            model_name='reader',
            name='birth_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AlterField(
            model_name='reader',
            name='register_date',
            field=models.DateField(default=datetime.date(2018, 2, 9)),
        ),
    ]
