# Generated by Django 2.0.2 on 2018-03-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='mobilenumber',
            new_name='user_id',
        ),
    ]
