# Generated by Django 2.0.2 on 2018-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_intro',
            new_name='authorintro',
        ),
        migrations.AddField(
            model_name='book',
            name='catalog',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
