# Generated by Django 2.0.2 on 2018-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20180315_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcart',
            name='add_time',
        ),
        migrations.AddField(
            model_name='bookcart',
            name='add_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='record_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
