# Generated by Django 2.0.2 on 2018-03-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20180313_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcart',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book'),
        ),
    ]
