# Generated by Django 2.0.2 on 2018-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_auto_20180315_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_bg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_sm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='record_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bookcart',
            name='add_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
