# Generated by Django 2.0.2 on 2018-03-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_auto_20180315_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstoreup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=13)),
                ('bookname', models.CharField(blank=True, max_length=80)),
                ('add_date', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookstoreup',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book'),
        ),
    ]
