# Generated by Django 2.0.2 on 2018-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_auto_20180316_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoreup',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
