# Generated by Django 2.0.2 on 2018-03-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_auto_20180316_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcart',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
